name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest]

    steps:
    - name: Check out Latest Code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
        architecture: x64

    - name: Install Poetry
      uses: snok/install-poetry@v1.3
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true
        installer-parallel: true

    - name: Display Poetry Configuration
      run: |
        poetry env info
        poetry config --list

    - name: Cache Dependencies
      uses: actions/cache@v3
      id: poetry-cache
      with:
        path: .venv
        key: ${{ '{{' }} runner.os {{ '}}' }}-poetry-${{ '{{' }} hashFiles('**/poetry.lock') {{ '}}' }}
        restore-keys: |
         ${{ '{{' }} runner.os {{ '}}' }}-poetry-venv

    - name: Install Dependencies
      run: |
        make init

    - name: Run Pre-Commit Hooks
      run: |
        make pre-commit

    - name: Run Tests
      run: |
        make test
