name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        python-version: ['3.7', '3.8', '3.9']
        os: [ubuntu-latest]

    steps:
    - name: Check out Latest Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ '{{' }} matrix.python-version {{ '}}' }}
        architecture: x64

    - name: Upgrade pip
      run: |
        pip install --upgrade pip
        pip --version

    - name: Install Poetry
      run: |
        pipx install poetry
        poetry --version

    - name: Install Tox
      run: |
        pipx install tox
        tox --version

    - name: Install Dependencies
      run: |
        make init

    - name: Run Pre-Commit Hooks
      run: |
        pre-commit run --all-files --show-diff-on-failure --color=always

    - name: Run Tests
      run: |
        python -m tox
