name: Publish

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - name: Check out Latest Code
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64

    - name: Install Dependencies
      run: make gh-prod

    - name: Configure PYPI Token
      run: poetry config pypi-token.pypi ${{ '{{' }} secrets.PYPI_TOKEN {{ '}}' }}

    - name: Publish Package
      run: poetry publish --build
